format_options:  [['All Formats', 'fmt' ,'all'], ['Books', 'fmt' ,'a'],['Movies / TV', 'fmt' ,'g']]
format_label: 'Format'
stylesheet: 'ica.css'
logo_on_homepage: 'true'
homepage_logo: 'ica.png'
search_text: 'Search'
search_menu: 'Search'
default_loc: '101'
opac_toggle_default: 'Main'
additional_nav_links:
  - name: 'Library Home'
    href: 'http://library.interlochen.org/'
  - name: 'Search'
    href: 'http://search.ebscohost.com/login.aspx?authtype=ip,guest&profile=eds&groupid=main&custid=s8905647&direct=true&setup=1'
lists: []
