location_name: 'Youth Catalog | Interlochen Public Library | Traverse Area District Library'
format_options:  [['All Formats', 'fmt' ,'all'], ['Books', 'fmt' ,'a'],['Movies / TV', 'fmt' ,'g'],['Music', 'fmt' ,'j']]
format_label: 'Format'
stylesheet: 'ipl_youth.css'
logo: 'ipl-tree-logo.jpg'
search_text: 'Search'
search_menu: 'Search'
default_loc: '24'
slider_frequency: 10
lists:
  - name: 'ipl_youth_books_list'
    fancy_name: 'Books'
    search_params: {'loc' : '24',
                    'qtype' : 'shelf',
                    'shelving_location' : ['977','978','979','980','981','527','529','576','630'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: "Board Books"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=632&layout=grid&search_title=Board Books'
      - name: "JBR Pre-Readers (Orange)"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=977&layout=grid&search_title=JBR Pre-Readers (Orange)'
      - name: "JBR New Readers (Green)"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=978&layout=grid&search_title=JBR New Readers (Green)'
      - name: "JBR Rising Readers (Purple)"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=979&layout=grid&search_title=JBR Rising Readers (Purple)'
      - name: "JBR Transitional Readers (Blue)"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=980&layout=grid&search_title=JBR Transitional Readers (Blue)'
      - name: "JBR Independent Readers (Red)"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=981&layout=grid&search_title=JBR Independent Readers (Red)'
      - name: "Juvenile Collection"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=527&layout=grid&search_title=Juvenile Collection'
      - name: "Juvenile Easy"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=529&layout=grid&search_title=Juvenile Easy'
      - name: "Early Learners"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=576&layout=grid&search_title=Early Learners'
      - name: "Juvenile Series"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=630&layout=grid&search_title=Juvenile Series'
      - name: "Juvenile Audiobooks"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=571&shelving_location[]=579&layout=grid&search_title=Juvenile Audiobooks'
  - name: 'ipl_youth_video_list'
    fancy_name: 'Video'
    search_params: {'loc' : '24',
                    'qtype' : 'shelf',
                    'shelving_location' : ['599','771','516'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: "Juvenile DVD"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=599&layout=grid&search_title=Juvenile DVD'
      - name: "Juvenile Digital Video Disc"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=771&layout=grid&search_title=Juvenile Digital Video Disc'
      - name: "Children's Videos"
        url: "/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=516&layout=grid&search_title=Children's Videos"
