location_name: 'Interlochen Public Library | Traverse Area District Library'
format_options:  [['All Formats', 'fmt' ,'all'], ['Books', 'fmt' ,'a'],['Movies / TV', 'fmt' ,'g'],['Music', 'fmt' ,'j']]
format_label: 'Format'
stylesheet: 'ipl.css'
logo: 'logo-clock-only.png'
search_text: 'Search'
search_menu: 'Search'
default_loc: '24'
slider_frequency: 10
lists:
  - name: 'ipl_books_list'
    fancy_name: 'Books'
    search_params: {'loc' : '24',
                    'qtype' : 'shelf',
                    'shelving_location' : ['510','975','976','614','615','612','616','613','537'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: "Adult"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=510&layout=grid&search_title=Adult'
  - name: 'ipl_av_list'
    fancy_name: 'Audio/Video'
    search_params: {'loc' : '24',
                    'qtype' : 'shelf',
                    'shelving_location' : ['521','517'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: "DVDs"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=521&layout=grid&search_title=DVDs'
      - name: "Music CDs"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=517&layout=grid&search_title=Music CDs'
