location_name: 'Interlochen Public Library | Traverse Area District Library'
format_options:  [['All Formats', 'fmt' ,'all'], ['Books', 'fmt' ,'a'],['Movies / TV', 'fmt' ,'g'],['Music', 'fmt' ,'j']]
format_label: 'Format'
stylesheet: 'ipl.css'
logo: 'logo-clock-only.png'
search_text: 'Search'
search_menu: 'Search'
default_loc: '24'
slider_frequency: 10
lists:
  - name: 'ipl_books_list'
    fancy_name: 'Books'
    search_params: {'loc' : '24',
                    'qtype' : 'shelf',
                    'shelving_location' : ['510','975','976','614','615','612','616','613','537'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: "Adult"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=510&layout=grid&search_title=Adult'
      - name: "Audiobooks"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=518&layout=grid&search_title=Audiobooks'
      - name: "MP3 CD Audiobooks"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=680&layout=grid&search_title=MP3 CD Audiobooks'
      - name: "Large Print"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=534&layout=grid&search_title=Large Print'
      - name: "Mass-Market Paperbacks"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=537&layout=grid&search_title=Mass-Market Paperbacks'
  - name: 'ipl_video_list'
    fancy_name: 'Movies'
    search_params: {'loc' : '24',
                    'qtype' : 'shelf',
                    'shelving_location' : ['521'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: "Movies"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=521&layout=grid&search_title=Movies'
      - name: "Television Series and Box Sets"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=779&layout=grid&search_title=Television Series and Box Sets'
  - name: 'ipl_music_list'
    fancy_name: 'Music (unfortunately this shelving location has audiobooks too)'
    search_params: {'loc' : '24',
                    'qtype' : 'shelf',
                    'shelving_location' : ['517'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: "Music CDs"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=517&layout=grid&search_title=Music CDs'
