location_name: 'Kingsley Branch | Traverse Area District Library'
format_options:  [['All Formats', 'fmt' ,'all'], ['Books', 'fmt' ,'a'],['Movies / TV', 'fmt' ,'g'],['Music', 'fmt' ,'j']]
format_label: 'Format'
stylesheet: 'kbl.css'
logo: 'logo-clock-only.png'
search_text: 'Search'
search_menu: 'Search'
default_loc: '25'
slider_frequency: 10
lists:
  - name: 'youth_ya_books_list'
    fancy_name: 'Youth & Teens'
    search_params: {'loc' : '25',
                    'qtype' : 'shelf',
                    'shelving_location' : ['527','529','791','792','563'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: "Juvenile"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=25&shelving_location[]=527&layout=grid&search_title=Juvenile'
      - name: "Juvenile Easy"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=25&shelving_location[]=529&layout=grid&search_title=Juvenile Easy'
      - name: "Juvenile Fiction"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=25&shelving_location[]=791&layout=grid&search_title=Juvenile Fiction'
      - name: "Juvenile Non-fiction"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=25&shelving_location[]=792&layout=grid&search_title=Juvenile Non-fiction'
      - name: "Young Adult"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=25&shelving_location[]=563&layout=grid&search_title=Young Adult'
  - name: 'adult_list'
    fancy_name: 'Adults'
    search_params: {'loc' : '25',
                    'qtype' : 'shelf',
                    'shelving_location' : ['510','975','976','689','690'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: "Books"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=25&shelving_location[]=510&layout=grid&search_title=Books'
      - name: "Audiobooks"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=25&shelving_location[]=518&shelving_location[]=584&layout=grid&search_title=Audiobooks'
      - name: "Large Print"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=25&shelving_location[]=534&layout=grid&search_title=Large Print'
      - name: "New Fiction"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=25&shelving_location[]=689&layout=grid&search_title=New Fiction'
      - name: "New Non-fiction"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=25&shelving_location[]=690&layout=grid&search_title=New Non-fiction'
  - name: 'audiovisual_list'
    fancy_name: 'Audio/Visual'
    search_params: {'loc' : '25',
                    'qtype' : 'shelf',
                    'shelving_location' : ['517','583','521','586'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: "DVDs"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=25&shelving_location[]=521&shelving_location[]=586&layout=grid&search_title=DVDs'
      - name: "Children's Videos"
        url: "/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=25&shelving_location[]=516&layout=grid&search_title=Children's Videos"
      - name: "Music CDs"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=25&shelving_location[]=517&shelving_location[]=583&layout=grid&search_title=Music CDs'
