format_options:  [['All YA Materials', 'shelving_location', '970']]
format_label: 'Format'
stylesheet: 'kcl_teen.css'
search_text: 'Search'
search_menu: 'Search'
slider_frequency: 10
default_loc: '44'
opac_toggle_default: 'Teen'
lists:
  - name: 'kcl_teen_carousel_1'
    fancy_name: 'Queens and Kingdoms'
    search_params: {'loc' : '44',
                    'qtype' : 'keyword',
                    'query' : '',
                    'fiction' : 'true',
                    'fmt' : '970',
                    'subjects' : ['Kings, queens, rulers, etc Fiction'],
                    'sort' : 'pubdateDESC',
                  }
  - name: 'kcl_teen_carousel_2'
    fancy_name: 'Hot Topics'
    search_params: {'loc' : '44',
                    'qtype' : 'keyword',
                    'query' : '',
                    'fmt' : '970',
                    'min_score' : '1',
                    'fiction' : 'false',
                    'sort' : 'pubdateDESC',
                   }
