format_options:  [["All Kids' Materials", "shelving_location", "956,957,958"]]
format_label: 'Format'
stylesheet: 'kcl_youth.css'
search_text: 'Search'
search_menu: 'Search'
slider_frequency: 10
default_loc: '44'
opac_toggle_default: 'Youth'
lists:
  - name: 'kcl_yout_list_1'
    fancy_name: 'New Juvenile Books'
    search_params: {'loc' : '44',
                    'qtype' : 'shelf',
                    'sort' : 'pubdateDESC',
                    'query' : '',
                    'shelving_location' : ['956'],
                    'canned' : 'true',
                    'sort' : 'pubdateDESC',
                  }
  - name: 'kcl_youth_list_2'
    fancy_name: 'New Juvenile Picturebooks'
    search_params: {'loc' : '44',
                    'qtype' : 'shelf',
                    'sort' : 'pubdateDESC',
                    'query' : '',
                    'shelving_location' : ['957'],
                    'canned' : 'true',
                    'sort' : 'pubdateDESC',
                  }
