format_options:  [["All Kids' Materials", "shelving_location", "956,957,958"]]
format_label: 'Format'
stylesheet: 'kcl_youth.css'
search_text: 'Search'
search_menu: 'Search'
slider_frequency: 10
default_loc: '44'
opac_toggle_default: 'Youth'
lists:
  - name: 'kcl_youth_slider_1'
    fancy_name: 'Valentines Day Books'
    search_params: {'loc' : '44',
                    'qtype' : 'keyword',
                    'fmt' : '956,957,958',
                    'query' : 'valentines day',
                    'canned' : 'true',
                    'sort' : 'relevancy',
                  }
    searches:
      - name: "Juvenile"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=44&shelving_location[]=956&search_title=Juvenile'
      - name: "Picture Books (JE)"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=44&shelving_location[]=957&search_title=Picture Books (JE)'
      - name: "Easy Readers"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=44&shelving_location[]=958&search_title=Easy Readers'
  - name: 'kcl_youth_slider_2'
    fancy_name: 'Chinese'
    search_params: {'loc' : '44',
                    'qtype' : 'keyword',
                    'query' : 'chinese',
                    'fmt' : '956,957,958',
                    'canned' : 'true',
                    'sort' : 'relevancy',
                   }
