format_options:  [['All Formats', 'fmt' ,'all'], ['Books', 'fmt' ,'a'],['Movies / TV', 'fmt' ,'g']]
format_label: 'Format'
stylesheet: 'kcl.css'
search_text: 'Search'
search_menu: 'Search'
slider_frequency: 10
default_loc: '44'
opac_toggle_default: 'Main'
lists:
  - name: 'kcl_list_1'
    fancy_name: 'New Books'
    search_params: {'loc' : '44',
                    'qtype' : 'shelf',
                    'shelving_location' : '1032',
                    'shelving_location' : '1044',
                    'shelving_location' : '1047',
                    'shelving_location' : '1048',
                    'shelving_location' : '1049',
                    'shelving_location' : '1050',
                    'sort' : 'pubdateDESC',
                    'search_title' : 'Books',
                  }
  - name: 'kcl_list_2'
    fancy_name: 'New Audiobooks'
    search_params: {'loc' : '44',
                    'qtype' : 'shelf',
                    'sort' : 'pubdateDESC',
                    'query' : '',
                    'shelving_location' : '950',
                    'search_title' : 'Audiobooks',
                  }
  - name: 'kcl_list_3'
    fancy_name: 'New Videos'
    search_params: {'loc' : '44',
                    'qtype' : 'shelf',
                    'sort' : 'pubdateDESC',
                    'query' : '',
                    'shelving_location' : '951',
                    'search_title' : 'All Videos',
                  }
