application_name: 'kalkaska-youth-catalog'
format_options:  [['All YA Materials', 'shelving_location', '970']]
format_label: 'Format'
stylesheet: 'kcl_teen.css'
logo: 'kcl-logo.jpg'
search_text: 'Search'
search_menu: 'Search'
slider_frequency: 10
default_loc: '44'
opac_toggle_default: 'Teen'
lists:
  - name: 'kcl_teen_books_list'
    fancy_name: 'Featured Books'
    search_params: {'loc' : '44',
                    'qtype' : 'shelf',
                    'shelving_location' : ['970'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC',
                  }
    searches:
      - name: "Young Adult Books"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=44&shelving_location[]=970&layout=grid&search_title=Young Adult Books'
  - name: 'kcl_teen_star_wars'
    fancy_name: 'Featured Display: Star Wars'
    search_params: {'loc' : '44',
                    'qtype' : 'keyword',
                    'query' : 'star wars',
                    'shelving_location' : ['970'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'min_score' : '1'
                   }
