format_options:  [["All Kids' Materials", "shelving_location", "956,957,958"]]
format_label: 'Format'
stylesheet: 'kcl_youth.css'
logo: 'kcl-logo.jpg'
search_text: 'Search'
search_menu: 'Search'
slider_frequency: 10
default_loc: '44'
opac_toggle_default: 'Youth'
lists:
  - name: 'kcl_youth_books_list'
    fancy_name: 'Featured Books'
    search_params: {'loc' : '44',
                    'qtype' : 'shelf',
                    'shelving_location' : ['956','957','958'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC',
                  }
    searches:
      - name: "Juvenile"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=44&shelving_location[]=956&layout=grid&search_title=Juvenile'
      - name: "Picture Books (JE)"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=44&shelving_location[]=957&layout=grid&search_title=Picture Books (JE)'
      - name: "Easy Readers"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=44&shelving_location[]=958&layout=grid&search_title=Easy Readers'
  - name: 'kcl_youth_star_wars'
    fancy_name: 'Featured Display: Star Wars'
    search_params: {'loc' : '44',
                    'qtype' : 'keyword',
                    'query' : 'star wars',
                    'shelving_location' : ['956','957','958'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'min_score' : '1'
                   }
