format_options:  [["All Kids' Materials", "shelving_location", "956,957,958"]]
format_label: 'Format'
stylesheet: 'kcl_youth.css'
search_text: 'Search'
search_menu: 'Search'
slider_frequency: 10
default_loc: '44'
opac_toggle_default: 'Youth'
default_search_display: 'list'
lists:
  - name: 'kcl_youth_list_1'
    fancy_name: 'New Juvenile Books'
    search_params: {'loc' : '44',
                    'qtype' : 'shelf',
                    'sort' : 'pubdateDESC',
                    'query' : '',
                    'shelving_location' : ['956'],
                    'canned' : 'true',
                    'sort' : 'pubdateDESC',
                  }
  - name: 'kcl_youth_list_2'
    fancy_name: 'New Juvenile Picturebooks'
    search_params: {'loc' : '44',
                    'qtype' : 'shelf',
                    'sort' : 'pubdateDESC',
                    'query' : '',
                    'shelving_location' : ['957'],
                    'canned' : 'true',
                    'sort' : 'pubdateDESC',
                  }
is_opac: true
is_opac_light: true
opac_toggle: [{'name': 'Main', 'url': 'https://kclopac.app.tadl.org/main/index'},{'name': 'Youth', 'url': 'https://kclyouthopac.app.tadl.org/main/index'},{'name': 'Teen', 'url': 'https://kclteenopac.app.tadl.org/main/index'}]
