is_opac: true
is_opac_light: true
opac_wake_message: 'Press any key or move mouse to search the catalog'
screen_saver_milliseconds: 15000
screen_saver:
  - url: 'https://old.tadl.org/wp-content/uploads/2018/02/opac_3.jpg'
  - url: 'https://old.tadl.org/wp-content/uploads/2018/02/opac_2.jpg'
  - url: 'https://old.tadl.org/wp-content/uploads/2018/03/TADL_OPAC_Yep_2018.jpg'
  - url: 'https://old.tadl.org/wp-content/uploads/2020/09/OPAC_sep_social.jpg'
  - url: 'https://old.tadl.org/wp-content/uploads/2021/10/opac-challenges.png'
  - url: 'https://www.tadl.org/sites/default/files/2022-10/OPAC_homework.png'
  - url: 'https://www.tadl.org/sites/default/files/2022-10/Website.png'
  - url: 'https://www.tadl.org/sites/default/files/2022-10/OPAC_beanstack.png'
shelf_lock:
  shelves: [510,618,975,976,680,783,683,518,584,769,525,569,534,535,789,619,797,620,621,544,546,590,551,552,553,554,575,1,1001,1089]
  location: '23'
  default_activated: false
  text: 'Limit to Adult at Woodmere'
location_name: 'Traverse City Library | Traverse Area District Library'
format_options:  [['All Formats', 'fmt' ,'all'], ['Books', 'fmt' ,'a'],['Large Print', 'shelving_location', '534'],['Movies / TV', 'fmt' ,'g'],['Music', 'fmt' ,'j'],['Music - Vinyl','shelving_location','533'],['Audiobooks','shelving_location','515,518,546,571,572,582,584,590,597,680,1090'],['- CD Audiobooks', 'shelving_location', '518,584'],['- MP3 CD Audiobooks', 'shelving_location', '680'],['- Playaway Audiobooks','shelving_location','546,590'],['Youth', 'shelving_location', '981,978,977,979,980,516,593,527,571,770,771,529,528,791,530,792,531,795,794,793,532,542,589,549,670'],['Teen','shelving_location','786,787,572,563,564,565,566,802,998,999,1000,1052,1053,1054'],['Sheet Music','shelving_location','575'],['Board Games', 'shelving_location', '1059'],['Library of Things', 'shelving_location', '1006,1026,514']]
#format_options_unlocked: [['All Formats', 'fmt' ,'all'], ['Books', 'fmt' ,'a'],['Movies / TV', 'fmt' ,'g'],['Music', 'fmt' ,'j']]
format_label: 'Format'
#format_label_unlocked: 'Format'
stylesheet: 'woodmere.css'
search_text: 'Search'
#search_text_unlocked: 'Search'
default_search_display: 'list'
search_menu: 'Search'
default_loc: '23'
slider_frequency: 10
additional_nav_links:
  - name: 'Reserve a Computer'
    href: 'http://pcres.lib.tadl.org/reserve.pl'
lists:
  - name: 'wood_new_fic_list'
    fancy_name: 'New Fiction'
    search_params: {'loc' : '23',
                    'qtype' : 'shelf',
                    'shelving_location' : ['619'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: "New Fiction"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=619&search_title=New Fiction'
      - name: "Adult Fiction"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=975&search_title=Adult Fiction'
      - name: "Large Print"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=534&search_title=Large Print'
      - name: "Browsing HOT Titles"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=683&search_title=Browsing HOT Titles'
  - name: 'wood_new_nonfic_list'
    fancy_name: 'New Non-fiction'
    search_params: {'loc' : '23',
                    'qtype' : 'shelf',
                    'shelving_location' : ['621'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: "New Non-fiction"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=621&search_title=New Non-fiction'
      - name: "Non-fiction"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=976&search_title=Non-fiction'
      - name: "Oversize"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=544&search_title=Oversize'
  - name: 'wood_audiobooks_list'
    fancy_name: 'Audiobooks'
    search_params: {'loc' : '23',
                    'qtype' : 'shelf',
                    'shelving_location' : ['515','518','546','571','572','582','584','590','597','680','1090'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: "Audiobooks"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=584&shelving_location[]=518&shelving_location[]=515&shelving_location[]=546&shelving_location[]=571&shelving_location[]=572&shelving_location[]=582&&shelving_location[]=590&shelving_location[]=597&&shelving_location[]=680&shelving_location[]=1090&search_title=Audiobooks'
      - name: "Audiobooks on MP3 CD"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=680&search_title=Audiobooks on MP3 CD'
      - name: "Playaways"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=546&shelving_location[]=590&search_title=Playaways'
