is_opac: true
is_opac_light: true
opac_wake_message: 'Press any key or move mouse to search the catalog'
screen_saver_milliseconds: 15000
screen_saver:
  - url: 'https://www.tadl.org/wp-content/uploads/2018/02/opac_3.jpg'
  - url: 'https://www.tadl.org/wp-content/uploads/2018/02/opac_2.jpg'
  - url: 'https://www.tadl.org/wp-content/uploads/2018/03/TADL_OPAC_Yep_2018.jpg'
  - url: 'https://www.tadl.org/wp-content/uploads/2021/06/SRC2021_OPAC2.jpg'
location_name: 'East Bay Branch | Traverse Area District Library'
register_location_name: 'East Bay Branch Library'
format_options: [['All Formats','fmt','all'],['Books','fmt','a'],['Large Print','fmt','large_print'],['Audiobooks','shelving_location','515,518,546,571,572,582,584,590,597,680'],['Movies / TV','fmt','g'],['Music','fmt','j'],['STEM Kits','shelving_location','1058']]
format_label: 'Format'
stylesheet: 'ebb.css'
search_text: 'Search'
search_menu: 'Search'
default_loc: '28'
slider_frequency: 10
lists:
  - name: 'ebb_youth_ya_list'
    fancy_name: 'Youth & Young Adult'
    search_params: {'loc' : '28',
                    'qtype' : 'shelf',
                    'shelving_location' : ['1052','1053','527','791','792'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: "Juvenile Collection"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=28&shelving_location[]=527&search_title=Juvenile Collection'
      - name: "Juvenile Fiction"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=28&shelving_location[]=791&search_title=Juvenile Fiction'
      - name: "Juvenile Nonfiction"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=28&shelving_location[]=792&search_title=Juvenile Nonfiction'
      - name: "Juvenile Easy"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=28&shelving_location[]=529&search_title=Juvenile Easy'
      - name: "Young Adult Fiction"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=28&shelving_location[]=1052&search_title=Young Adult Fiction'
      - name: "Young Adult Nonfiction"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=28&shelving_location[]=1053&search_title=Young Adult Nonfiction'
  - name: 'ebb_books_list'
    fancy_name: 'Books'
    search_params: {'loc' : '28',
                    'qtype' : 'shelf',
                    'shelving_location' : ['975','976'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: "Adult Fiction"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=28&shelving_location[]=975&search_title=Adult Fiction'
      - name: "Adult Nonfiction"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=28&shelving_location[]=976&search_title=Adult Nonfiction'
      - name: "Audiobooks"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=28&shelving_location[]=518&shelving_location[]=584&search_title=Audiobooks'
      - name: "Large Print"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=28&shelving_location[]=534&search_title=Large Print'
  - name: 'ebb_dvd_list'
    fancy_name: 'Video'
    search_params: {'loc' : '28',
                    'qtype' : 'shelf',
                    'shelving_location' : ['586','521'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: "All Videos"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=28&shelving_location[]=586&shelving_location[]=521&search_title=All Videos'
