is_opac: true
is_opac_light: true
summer_reading: 'false'
opac_wake_message: 'Press any key or move mouse to search the catalog'
screen_saver_milliseconds: 15000
screen_saver:
  - url: 'https://old.tadl.org/wp-content/uploads/2018/02/opac_3.jpg'
  - url: 'https://old.tadl.org/wp-content/uploads/2018/02/opac_2.jpg'
  - url: 'https://old.tadl.org/wp-content/uploads/2018/03/TADL_OPAC_Yep_2018.jpg'
location_name: 'Youth Catalog | Interlochen Public Library | Traverse Area District Library'
register_location_name: 'Interlochen Public Library'
shelf_lock:
  shelves: [578,981,978,977,979,980,632,516,576,594,527,571,770,599,771,529,791,813,809,817,530,792,531,532,598,597,596,630]
  location: '24'
  default_activated: true
  text: 'Limit to Youth items'
format_options:  [['All Formats', 'fmt' ,'all'], ['Books', 'fmt' ,'a'],['Movies / TV', 'fmt' ,'g'],['Music', 'fmt' ,'j']]
format_label: 'Format'
stylesheet: 'ipl_youth.css'
logo: 'ipl-tree-logo.jpg'
error_image: 'ipl-tree-logo.jpg'
search_text: 'Search'
search_menu: 'Search'
default_loc: '24'
opac_toggle: [{'name': 'Main', 'url': 'https://interlochen.opac.tadl.org/main/index'},{'name': 'Youth', 'url': 'https://interlochen-youth.opac.tadl.org/main/index'}]
opac_toggle_default: 'Youth'
slider_frequency: 10
lists:
  - name: 'ipl_youth_books_list'
    fancy_name: 'Books'
    search_params: {'loc' : '24',
                    'qtype' : 'shelf',
                    'shelving_location' : ['977','978','979','980','981','527','529','576','630'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: "Board Books"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=632&search_title=Board Books'
      - name: "JBR Pre-Readers (Orange)"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=977&search_title=JBR Pre-Readers (Orange)'
      - name: "JBR New Readers (Green)"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=978&search_title=JBR New Readers (Green)'
      - name: "JBR Rising Readers (Purple)"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=979&search_title=JBR Rising Readers (Purple)'
      - name: "JBR Transitional Readers (Blue)"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=980&search_title=JBR Transitional Readers (Blue)'
      - name: "JBR Independent Readers (Red)"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=981&search_title=JBR Independent Readers (Red)'
      - name: "Juvenile Collection"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=527&search_title=Juvenile Collection'
      - name: "Juvenile Easy"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=529&search_title=Juvenile Easy'
      - name: "Early Learners"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=576&search_title=Early Learners'
      - name: "Juvenile Series"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=630&search_title=Juvenile Series'
      - name: "Juvenile Audiobooks"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=571&shelving_location[]=579&search_title=Juvenile Audiobooks'
  - name: 'ipl_youth_video_list'
    fancy_name: 'Video'
    search_params: {'loc' : '24',
                    'qtype' : 'shelf',
                    'shelving_location' : ['599','771','516'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: "Juvenile DVD"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=599&search_title=Juvenile DVD'
      - name: "Juvenile Digital Video Disc"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=771&search_title=Juvenile Digital Video Disc'
      - name: "Children's Videos"
        url: "/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=24&shelving_location[]=516&search_title=Children's Videos"
