format_options:  [['All YA Materials', 'shelving_location', '970']]
format_label: 'Format'
stylesheet: 'kcl_teen.css'
search_text: 'Search'
search_menu: 'Search'
slider_frequency: 10
default_loc: '44'
opac_toggle_default: 'Teen'
default_search_display: 'list'
lists:
  - name: 'kcl_teen_list_1'
    fancy_name: 'New Teen Books'
    search_params: {'loc' : '44',
                    'qtype' : 'shelf',
                    'shelving_location' : ['970'],
                    'sort' : 'pubdateDESC',
                    'canned' : 'true',
                  }
is_opac: true
is_opac_light: true
opac_toggle: [{'name': 'Main', 'url': 'https://kclopac.app.tadl.org/main/index'},{'name': 'Youth', 'url': 'https://kclyouthopac.app.tadl.org/main/index'},{'name': 'Teen', 'url': 'https://kclteenopac.app.tadl.org/main/index'}]
