format_options:  [['All Formats', 'fmt' ,'all'], ['Books', 'fmt' ,'a'],['Movies / TV', 'fmt' ,'g']]
format_label: 'Format'
stylesheet: 'kcl.css'
search_text: 'Search'
search_menu: 'Search'
slider_frequency: 10
default_loc: '44'
opac_toggle_default: 'Main'
default_search_display: 'list'
lists:
  - name: 'kcl_list_1'
    fancy_name: 'New Books'
    search_params: {'loc' : '44',
                    'qtype' : 'shelf',
                    'shelving_location' : ['1032', '1044', '1047', '1048', '1049', '1050'],
                    'sort' : 'pubdateDESC',
                    'canned' : 'true',
                  }
  - name: 'kcl_list_2'
    fancy_name: 'New Audiobooks'
    search_params: {'loc' : '44',
                    'qtype' : 'shelf',
                    'sort' : 'pubdateDESC',
                    'query' : '',
                    'shelving_location' : ['950'],
                    'canned' : 'true',
                  }
  - name: 'kcl_list_3'
    fancy_name: 'New Videos'
    search_params: {'loc' : '44',
                    'qtype' : 'shelf',
                    'sort' : 'pubdateDESC',
                    'query' : '',
                    'shelving_location' : ['951'],
                    'canned' : 'true',
                  }
is_opac: true
is_opac_light: true
opac_toggle: [{'name': 'Main', 'url': 'https://kclopac.app.tadl.org/main/index'},{'name': 'Youth', 'url': 'https://kclyouthopac.app.tadl.org/main/index'},{'name': 'Teen', 'url': 'https://kclteenopac.app.tadl.org/main/index'}]
