is_opac: true
is_opac_light: true
opac_wake_message: 'Press any key or move mouse to search the catalog'
screen_saver_milliseconds: 15000
screen_saver:
  - url: 'https://www.tadl.org/sites/default/files/2024-12/Cooking%20-%20OPAC.png'
  - url: 'https://www.tadl.org/sites/default/files/2024-08/waves%20OPAC.png'
  - url: 'https://www.tadl.org/sites/default/files/2023-07/More%20time.png'
  - url: 'https://www.tadl.org/sites/default/files/2023-07/Search%202023.png'
  - url: 'https://www.tadl.org/sites/default/files/2022-10/OPAC_homework.png'
  - url: 'https://www.tadl.org/sites/default/files/2023-11/100-checkouts-holds.png'
  - url: 'https://www.tadl.org/sites/default/files/2023-12/Social.png'
  - url: 'https://www.tadl.org/sites/default/files/2023-12/History.png'
  - url: 'https://www.tadl.org/sites/default/files/2024-06/opac_waves.png'
  - url: 'https://www.tadl.org/sites/default/files/2024-06/opac_Beanstack-new.png'
  - url: 'https://www.tadl.org/sites/default/files/2024-06/opac_CAC.png'
location_name: 'Sight & Sound | Traverse City Library | Traverse Area District Library'
shelf_lock:
  shelves: [982,983,682,684,808,517,583,985,521,586,800,987,801,772,989,774,991,588,580,773,821,686,687,781,997,993,671,674,994,556,557,788,617,778,779,995,814,777,996,1042,533]
  location: '23'
  default_activated: true
  text: 'Limit to Sight & Sound items'
format_options:  [['All Formats', 'fmt' ,'all'], ['Books', 'fmt' ,'a'],['Movies / TV', 'fmt' ,'g'],['Music', 'fmt' ,'j'],['Music - Vinyl','shelving_location','533'],['Video Games','shelving_location', '777'],['Library of Things', 'shelving_location', '1006,1026'],['Sheet Music','fmt','notated_music']]
format_label: 'Format'
stylesheet: 'ss.css'
default_search_display: 'list'
search_text: 'Search'
search_menu: 'Search'
slider_frequency: 10
default_loc: '23'
additional_nav_links:
  - name: 'Book a Meeting Room'
    href: 'https://events.tadl.org/reserve-room'
lists:
  - name: 'wood_ss_movie_list'
    fancy_name: 'Movies & TV'
    search_params: {'loc' : '23',
                    'qtype' : 'shelf',
                    'shelving_location' : ['682','687','814'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: "Hot DVDs"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=682&search_title=Hot DVDs'
      - name: "New DVDs"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=687&search_title=New DVDs'
      - name: "TC Film Festival"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=778&search_title=TC Film Festival'
      - name: "Educational Television"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=801&search_title=Educational Television'
      - name: "Action/Adventure"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=982&search_title=Action/Adventure'
      - name: "Comedy"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=808&search_title=Comedy'
      - name: "Crime/Mystery"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=985&search_title=Crime/Mystery'
      - name: "Documentary"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=800&search_title=Documentary'
      - name: "Drama"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=987&search_title=Drama'
      - name: "Avant-Garde"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=983&search_title=Avant-Garde'
      - name: "Family"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=772&search_title=Family'
      - name: "Fantasy"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=989&search_title=Fantasy'
      - name: "Foreign"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=774&search_title=Foreign'
      - name: "Horror"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=991&search_title=Horror'
      - name: "Music"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=773&search_title=Music'
      - name: "Musicals"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=821&search_title=Musicals'
      - name: "Opera"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=781&search_title=Opera'
      - name: "Performing Arts"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=997&search_title=Performing Arts'
      - name: "Romance"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=993&search_title=Romance'
      - name: "Science Fiction"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=994&search_title=Science Fiction'
      - name: "TV"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=779&search_title=TV'
      - name: "British TV"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=1042&search_title=British TV'
      - name: "E-TV"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=801&search_title=E-TV'
      - name: "Thriller"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=995&search_title=Thriller'
      - name: "Western"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=996&search_title=Western'
  - name: 'wood_ss_music_list'
    fancy_name: 'Music'
    search_params: {'loc' : '23',
                    'qtype' : 'shelf',
                    'shelving_location' : ['686'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: "New Music"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=686&search_title=New%20Music'
      - name: "Hot Tunes"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=684&search_title=Hot%20Tunes'
      - name: 'Avant-garde'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&fmt=j&genres[]=Avant-garde&search_title=Avant-garde&genre_lock=Avant-garde'
      - name: 'Blues'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&fmt=j&genres[]=Blues&search_title=Blues&genre_lock=Blues'
      - name: 'Classical'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&fmt=j&genres[]=Classical&search_title=Classical&genre_lock=Classical'
      - name: 'Comedy/Spoken'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&genres[]=Comedy/Spoken&search_title=Comedy/Spoken&genre_lock=Comedy/Spoken'
      - name: 'Country'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&fmt=j&genres[]=Country&search_title=Country&genre_lock=Country'
      - name: 'Easy Listening'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&fmt=j&genres[]=Easy Listening&search_title=Easy Listening&genre_lock=Easy Listening'
      - name: 'Electronic'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&fmt=j&genres[]=Electronic&search_title=Electronic&genre_lock=Electronic'
      - name: 'Folk'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&fmt=j&genres[]=Folk&search_title=Folk&genre_lock=Folk'
      - name: 'International'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&fmt=j&genres[]=International&search_title=International&genre_lock=International'
      - name: 'Jazz'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&fmt=j&genres[]=Jazz&search_title=Jazz&genre_lock=Jazz'
      - name: 'Latin'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&fmt=j&genres[]=Latin&search_title=Latin&genre_lock=Latin'
      - name: 'Local'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&fmt=j&genres[]=Local&search_title=Local&genre_lock=Local'
      - name: 'New Age'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&fmt=j&genres[]=New Age&search_title=New Age&genre_lock=New Age'
      - name: 'Opera'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&fmt=j&genres[]=Opera&search_title=Opera&genre_lock=Opera'
      - name: 'Pop/Rock'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&fmt=j&genres[]=Pop/Rock&search_title=Pop/Rock&genre_lock=Pop/Rock'
      - name: 'Rap'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&fmt=j&genres[]=Rap&search_title=Rap&genre_lock=Rap'
      - name: 'Reggae'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&fmt=j&genres[]=Reggae&search_title=Reggae&genre_lock=Reggae'
      - name: 'Religious'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&fmt=j&genres[]=Religious&search_title=Religious&genre_lock=Religious'
      - name: 'Rhythm and Blues'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&fmt=j&genres[]=Rhythm and Blues&search_title=Rhythm and Blues&genre_lock=Rhythm and Blues'
      - name: 'Vocal'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&fmt=j&genres[]=Vocal&search_title=Vocal&genre_lock=Vocal'
  - name: 'wood_ss_game_list'
    fancy_name: 'Games'
    search_params: {'loc' : '23',
                    'qtype' : 'shelf',
                    'shelving_location' : ['777'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: 'Nintendo Switch'
        url: '/main/search?query=GAME SWITCH&qtype=call_number&sort=pubdateDESC&loc=23'
      - name: 'Nintendo Wii'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&genres[]=Nintendo Wii video games.&search_title=Nintendo Wii&genre_lock=Nintendo Wii video games.'  
      - name: "Nintendo Wii U"
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&genres[]=Nintendo Wii U video games.&search_title=Nintendo Wii U&genre_lock=Nintendo Wii U video games.'
      - name: 'Nintendo 3DS'
        url: '/main/search?query=GAME 3DS&qtype=call_number&sort=pubdateDESC&loc=23'
      - name: 'PlayStation 5'
        url: '/main/search?query=GAME%20PS5&qtype=call_number&sort=pubdateDESC&loc=23'
      - name: 'PlayStation 4'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&genres[]=PlayStation 4 video games.&search_title=PlayStation 4&genre_lock=PlayStation 4 video games.'
      - name: 'PlayStation 3'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&genres[]=PlayStation 3 video games.&search_title=PlayStation 3&genre_lock=PlayStation 3 video games.'
      - name: 'PlayStation 2'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&genres[]=PlayStation 2 video games.&search_title=PlayStation 2&genre_lock=PlayStation 2 video games.'
      - name: 'Xbox One'
        url: '/main/search?query=GAME XBOXONE&qtype=call_number&sort=pubdateDESC&loc=23'
      - name: "Xbox 360"
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&genres[]=Xbox 360 video games.&search_title=Xbox 360&genre_lock=Xbox 360 video games.'
      - name: 'Xbox'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&genres[]=Xbox video games.&search_title=Xbox&genre_lock=Xbox video games.'
  - name: 'library_of_things'
    fancy_name: 'Library of Things'
    search_params: {'loc' : '22',
                  'qtype' : 'shelf',
                  'shelving_location' : ['1006','1026'],
                  'canned' : 'true',
                  'availability' : 'on',
                  'sort' : 'createDESC'}
