format_options:  [['All Formats', 'fmt' ,'all'], ['Books', 'fmt' ,'a'],['Movies / TV', 'fmt' ,'g'],['Music', 'fmt' ,'j']]
format_label: 'Format'
stylesheet: 'pcl.css'
logo: 'pcl-notext.jpg'
search_text: 'Search'
search_menu: 'Search'
default_loc: '26'
slider_frequency: 10
lists:
  - name: 'adult_list'
    fancy_name: 'Adults'
    search_params: {'loc' : '26',
                    'qtype' : 'shelf',
                    'shelving_location' : ['510','1'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
  - name: 'juvenile_list'
    fancy_name: 'Children'
    search_params: {'loc' : '26',
                    'qtype' : 'shelf',
                    'shelving_location' : ['527','529'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
  - name: 'dvd_list'
    fancy_name: 'Movies'
    search_params: {'loc' : '26',
                    'qtype' : 'shelf',
                    'shelving_location' : ['521','779','682'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
  - name: 'custom_list'
    fancy_name: 'Star Wars'
    search_params: {'loc' : '26',
                    'qtype' : 'keyword',
                    'canned' : 'true',
                    'query' : 'star wars',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC',
                    'min_score' : '1' }
    searches:
