format_options:  [['All Formats', 'fmt' ,'all'], ['Books', 'fmt' ,'a'],['Movies / TV', 'fmt' ,'g'],['Music', 'fmt' ,'j']]
format_label: 'Format'
stylesheet: 'pcl.css'
logo: 'pcl-notext.jpg'
search_text: 'Search'
search_menu: 'Search'
default_loc: '26'
slider_frequency: 10
lists:
  - name: 'fiction_list'
    fancy_name: 'Fiction'
    search_params: {'loc' : '26',
                    'qtype' : 'shelf',
                    'shelving_location' : ['510','511','618','619','620','976','975'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
  - name: 'nonfic_list'
    fancy_name: 'Non-fiction'
    search_params: {'loc' : '26',
                    'qtype' : 'shelf',
                    'shelving_location' : ['682','687','778','686','684'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
  - name: 'youth_list'
    fancy_name: 'Youth'
    search_params: {'loc' : '26',
                    'qtype' : 'shelf',
                    'shelving_location' : ['810','529','528','791','813','795','794','793','819'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
  - name: 'movies_list'
    fancy_name: 'Movies'
    search_params: {'loc' : '26',
                    'qtype' : 'shelf',
                    'shelving_location' : ['810','529','528','791','813','795','794','793','819'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
  - name: 'seasonal_list'
    fancy_name: 'Star Wars'
    search_params: {'loc' : '26',
                    'qtype' : 'keyword',
                    'canned' : 'true',
                    'query' : 'star wars',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC',
                    'min_score' : '1' }
    searches:
