format_options:  [['All Formats', 'fmt' ,'all'], ['Books', 'fmt' ,'a'],['Movies / TV', 'fmt' ,'g']]
format_label: 'Format'
stylesheet: 'sbbdl.css'
search_text: 'Search'
search_menu: 'Search'
slider_frequency: 10
default_loc: '46'
default_search_display: 'list'
#opac_toggle_default: 'Main'
lists:
  - name: 'sbbdl_new_fiction'
    fancy_name: 'New Fiction'
    search_params: {'loc' : '46',
                    'qtype' : 'shelf',
                    'shelving_location' : ['1011'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC',
                  }
  - name: 'sbbdl_new_movies'
    fancy_name: 'New Movies'
    search_params: {'loc' : '46',
                    'qtype' : 'shelf',
                    'shelving_location' : ['1020'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC',
                  }
  - name: 'sbbdl_new_juv'
    fancy_name: 'New Juvenile'
    search_params: {'loc' : '46',
                    'qtype' : 'shelf',
                    'shelving_location' : ['1217'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC',
                  }
