format_options:  [['All Formats', 'fmt' ,'all'], ['Books', 'fmt' ,'a'],['Movies / TV', 'fmt' ,'g']]
format_label: 'Format'
stylesheet: 'sbbdl.css'
search_text: 'Search'
search_menu: 'Search'
slider_frequency: 10
default_loc: '44'
opac_toggle_default: 'Main'
lists:
  - name: 'kcl_generic_books_list'
    fancy_name: 'Featured Books'
    search_params: {'loc' : '44',
                    'qtype' : 'shelf',
                    'shelving_location' : ['948','1'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC',
                  }
    searches:
      - name: "Books"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=44&shelving_location[]=948&shelving_location[]=1&search_title=Books'
      - name: "Large Print"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=44&shelving_location[]=959&search_title=Large Print'
  - name: 'kcl_generic_audiobooks_list'
    fancy_name: 'Featured Audiobooks'
    search_params: {'loc' : '44',
                    'qtype' : 'shelf',
                    'shelving_location' : ['950'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC',
                  }
    searches:
      - name: "Audiobooks"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=44&shelving_location[]=950&search_title=Audiobooks'
  - name: 'kcl_generic_audiovisual_list'
    fancy_name: 'Featured Movies & TV'
    search_params: {'loc' : '44',
                    'qtype' : 'shelf',
                    'shelving_location' : ['951'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC',
                  }
    searches:
      - name: "All Videos"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=44&shelving_location[]=951&search_title=All Videos'
