location_name: 'Traverse Area District Library'
format_options:  [['All Formats', 'fmt' ,'all'], ['Books', 'fmt' ,'a'],['Large Print', 'shelving_location', '534'],['Audiobooks','shelving_location','515,518,546,571,572,582,584,590,597,680'],['eBooks','fmt','ebooks'],['Movies / TV', 'fmt' ,'g'],['Music', 'fmt' ,'j'],['Video Games','shelving_location','777']]
format_label: 'Format'
default_search_display: 'list'
stylesheet: 'tadl.css'
logo_on_homepage: 'true'
homepage_logo: 'large_tadl_logo.png'
search_text: 'Search'
search_menu: 'Search'
tracked: 'true'
tracking_code: 'UA-75692003-1'
default_loc: '22'
summer_reading: 'true'
slider_frequency: 10
is_opac: true
additional_nav_links:
  - name: 'Website'
    href: 'http://www.tadl.org/'
lists:
  - name: 'tadl_books_list'
    fancy_name: 'New Books'
    search_params: {'loc' : '22',
                    'qtype' : 'shelf',
                    'shelving_location' : ['619','621'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: "New Fiction"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=619&search_title=New Fiction'
      - name: "New Non-fiction"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=621&search_title=New Non-fiction'
      - name: "Large Print"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=534&search_title=Large Print'
      - name: "Browsing HOT Titles"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=683&search_title=Browsing HOT Titles'
      - name: "Oversize"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=544&search_title=Oversize'
      - name: "Audiobooks"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=584&shelving_location[]=518&search_title=Audiobooks'
      - name: "Audiobooks on MP3 CD"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=680&search_title=Audiobooks on MP3 CD'
      - name: "Playaways"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=546&shelving_location[]=590&search_title=Playaways'
  - name: 'tadl_movies_list'
    fancy_name: 'New Movies & TV'
    search_params: {'loc' : '22',
                    'qtype' : 'shelf',
                    'shelving_location' : ['687','682'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: "Hot DVDs"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=682&search_title=Hot DVDs'
      - name: "New DVDs"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=687&search_title=New DVDs'
      - name: "TC Film Festival"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=778&search_title=TC Film Festival'
      - name: 'Animation'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=g&genres[]=Animation&search_title=Animation&genre_lock=Animation'
      - name: 'Family'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=g&genres[]=Family&search_title=Family&genre_lock=Family'
      - name: 'Comedy'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=g&genres[]=Comedy&search_title=Comedy&genre_lock=Comedy'
      - name: 'Documentary'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=g&genres[]=Documentary&search_title=Documentary&genre_lock=Documentary'
      - name: 'Horror'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=g&genres[]=Horror&search_title=Horror&genre_lock=Horror'
      - name: 'Music'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=g&genres[]=Music&search_title=Music&genre_lock=Music'
      - name: 'Romance'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=g&genres[]=Romance&search_title=Romance&genre_lock=Romance'
      - name: 'Science Fiction'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=g&genres[]=Science%20Fiction&search_title=Science%20Fiction&genre_lock=Science%20Fiction'
      - name: 'TV'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=g&genres[]=TV&search_title=TV&genre_lock=TV'
      - name: 'Western'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=g&genres[]=Western&search_title=Western&genre_lock=Western'
  - name: 'tadl_music_list'
    fancy_name: 'New Music'
    search_params: {'loc' : '22',
                    'qtype' : 'shelf',
                    'shelving_location' : ['686','684'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: "New Music"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=686&search_title=New%20Music'
      - name: "Hot Tunes"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=684&search_title=Hot%20Tunes'
      - name: 'Avant-garde'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Avant-garde&search_title=Avant-garde&genre_lock=Avant-garde'
      - name: 'Blues'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Blues&search_title=Blues&genre_lock=Blues'
      - name: 'Classical'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Classical&search_title=Classical&genre_lock=Classical'
      - name: 'Comedy/Spoken'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&genres[]=Comedy/Spoken&search_title=Comedy/Spoken&genre_lock=Comedy/Spoken'
      - name: 'Country'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Country&search_title=Country&genre_lock=Country'
      - name: 'Easy Listening'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Easy Listening&search_title=Easy Listening&genre_lock=Easy Listening'
      - name: 'Electronic'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Electronic&search_title=Electronic&genre_lock=Electronic'
      - name: 'Folk'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Folk&search_title=Folk&genre_lock=Folk'
      - name: 'International'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=International&search_title=International&genre_lock=International'
      - name: 'Jazz'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Jazz&search_title=Jazz&genre_lock=Jazz'
      - name: 'Latin'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Latin&search_title=Latin&genre_lock=Latin'
      - name: 'Local'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Local&search_title=Local&genre_lock=Local'
      - name: 'New Age'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=New Age&search_title=New Age&genre_lock=New Age'
      - name: 'Opera'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Opera&search_title=Opera&genre_lock=Opera'
      - name: 'Pop/Rock'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Pop/Rock&search_title=Pop/Rock&genre_lock=Pop/Rock'
      - name: 'Rap'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Rap&search_title=Rap&genre_lock=Rap'
      - name: 'Reggae'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Reggae&search_title=Reggae&genre_lock=Reggae'
      - name: 'Religious'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Religious&search_title=Religious&genre_lock=Religious'
      - name: 'Rhythm and Blues'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Rhythm and Blues&search_title=Rhythm and Blues&genre_lock=Rhythm and Blues'
      - name: 'Vocal'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Vocal&search_title=Vocal&genre_lock=Vocal'
