shelf_lock:
  shelves: [510,618,975,976,680,783,683,518,584,769,525,569,534,535,789,619,797,620,621,544,546,590,551,552,553,554,575,1]
  location: '23'
  default_activated: false
  text: 'Limit to Adult at Woodmere'
location_name: 'Woodmere (Main) Branch | Traverse Area District Library'
format_options:  [['All Formats', 'fmt' ,'all'], ['Books', 'fmt' ,'a'],['Large Print', 'shelving_location', '534'],['Movies / TV', 'fmt' ,'g'],['Music', 'fmt' ,'j'],['CD Audiobooks', 'shelving_location', '518,584'],['MP3 CD Audiobooks', 'shelving_location', '680'],['Playaway Audiobooks','shelving_location','546,590'],['Youth', 'shelving_location', '981,978,977,979,980,516,593,527,571,770,771,529,528,791,530,792,531,795,794,793,532,542,589,549,670'],['Teen','shelving_location','786,787,572,563,564,565,566,802'],['Sheet Music','shelving_location','575']]
#format_options_unlocked: [['All Formats', 'fmt' ,'all'], ['Books', 'fmt' ,'a'],['Movies / TV', 'fmt' ,'g'],['Music', 'fmt' ,'j']]
format_label: 'Format'
#format_label_unlocked: 'Format'
stylesheet: 'woodmere.css'
logo: 'logo-clock-only.png'
search_text: 'Search'
#search_text_unlocked: 'Search'
default_search_display: 'list'
search_menu: 'Search'
default_loc: '23'
slider_frequency: 10
computer_reservation_url: 'http://pcres.lib.tadl.org/reserve.pl'
lists:
  - name: 'wood_new_fic_list'
    fancy_name: 'New Fiction'
    search_params: {'loc' : '23',
                    'qtype' : 'shelf',
                    'shelving_location' : ['619'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: "New Fiction"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=619&search_title=New Fiction'
      - name: "Adult Fiction"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=975&search_title=Adult Fiction'
      - name: "Large Print"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=534&search_title=Large Print'
      - name: "Browsing HOT Titles"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=683&search_title=Browsing HOT Titles'
  - name: 'wood_new_nonfic_list'
    fancy_name: 'New Non-fiction'
    search_params: {'loc' : '23',
                    'qtype' : 'shelf',
                    'shelving_location' : ['621'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: "New Non-fiction"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=621&search_title=New Non-fiction'
      - name: "Non-fiction"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=976&search_title=Non-fiction'
      - name: "Oversize"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=544&search_title=Oversize'
  - name: 'wood_audiobooks_list'
    fancy_name: 'Audiobooks'
    search_params: {'loc' : '23',
                    'qtype' : 'shelf',
                    'shelving_location' : ['518','584'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: "Audiobooks"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=584&shelving_location[]=518&search_title=Audiobooks'
      - name: "Audiobooks on MP3 CD"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=680&search_title=Audiobooks on MP3 CD'
      - name: "Playaways"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=546&shelving_location[]=590&search_title=Playaways'
