shelf_lock:
  shelves: [571,810,529,528,791,813,795,794,793,819,809,817,818,516,593,771,589,542,770,792,549,527,815,530,531,532,977,978,979,980,981]
  location: '23'
  default_activated: true
  text: 'Limit to Youth items'
format_options: [['Juvenile', 'shelving_location', '516,527,528,529,530,531,532,542,549,571,589,593,770,771,791,792,793,794,795,809,810,813,815,817,818,819,977,978,979,980,981'],['Nonfiction', 'shelving_location', '792'],['Fiction', 'shelving_location', '528,529,791,793,794,795,810,813,819,977,978,979,980,981'],['Audiobooks', 'shelving_location', '571'],['Foreign Language', 'shelving_location', '809'],['Graphic Novels', 'shelving_location', '817'],['Holidays', 'shelving_location', '818'],['Movies', 'shelving_location', '516,593,771'],['Music', 'shelving_location', '770'],['Multimedia Kits', 'shelving_location', '542,589'],['Puppets', 'shelving_location', '549']]
stylesheet: 'youth.css'
logo: 'logo-clock-only.png'
slider_frequency: 60
lists:
  - name: 'movie_list'
    fancy_name: 'Movies'
    loc: '23'
    shelving_locations: ['516','593','771']
    searches:
      - name: "Movies and Videos"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=771&layout=grid&search_title=Movies and Videos'
  - name: 'fiction_list'
    fancy_name: 'Fiction'
    loc: '23'
    shelving_locations: ['810','529','528','791','813','795','794','793','819']
    searches:
      - name: "JE Concept Crates"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=810&layout=grid&search_title=JE%20Concept%20Crates'
      - name: "Juvenile Easy"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=529&layout=grid&search_title=Juvenile%20Easy'
      - name: "Juvenile Easy Plus"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=528&layout=grid&search_title=Juvenile%20Easy%20Plus'
      - name: "Juvenile Fiction"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=791&layout=grid&search_title=Juvenile%20Fiction'
      - name: "Juvenile Fiction Series"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=813&layout=grid&search_title=Juvenile%20Fiction%20Series'
      - name: "Juvenile Paperback - Blue"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=795&layout=grid&search_title=Juvenile%20Paperback%20-%20Blue'
      - name: "Juvenile Paperback - Pink"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=794&layout=grid&search_title=Juvenile%20Paperback%20-%20Pink'
      - name: "Juvenile Paperback - Red"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=793&layout=grid&search_title=Juvenile%20Paperback%20-%20Red'
      - name: "Favorite Characters"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=819&layout=grid&search_title=Favorite%20Characters'
  - name: 'readers_list'
    fancy_name: 'Beginning Readers'
    loc: '23'
    shelving_locations: ['977','978','979','980','981']
    searches:
      - name: "Pre-Reader (Orange)"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=977&layout=grid&search_title=Beginning%20Readers%20-%20Pre-Reader%20(Orange)'
      - name: "New Reader (Green)"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=978&layout=grid&search_title=Beginning%20Readers%20-%20New%20Reader%20(Green)'
      - name: "Rising Reader (Purple)"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=979&layout=grid&search_title=Beginning%20Readers%20-%20Rising%20Reader%20(Purple)'
      - name: "Transitional Reader (Blue)"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=980&layout=grid&search_title=Beginning%20Readers%20-%20Transitional%20Reader%20(Blue)'
      - name: "Independent Reader (Red)"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=23&shelving_location[]=981&layout=grid&search_title=Beginning%20Readers%20-%20Independent%20Reader%20(Red)'
