machine_readable: 'lib2mr.tadl.net'
public_catalog: 'https://ica.apps.tadl.org'
location_name: 'Interlochen Center for the Arts Library'
has_payments: 'false'
has_registration: 'false'
has_eresources: 'false'
account_only: 'true'
one_location: 'true'
