machine_readable: 'lib2mr.tadl.net'
public_catalog: 'https://myaccount.ica.tadl.net'
elastic_evergreen_url: 'https://elastic-evergreen-ica.apps.tadl.org/main/index.json?query='
elastic_locations: [['ICA-ACADEMIC', '102'],['ICA-MUSIC', '103']]
location_name: 'Interlochen Center for the Arts Library'
has_payments: 'false'
has_registration: 'false'
has_eresources: 'false'
account_only: 'true'
one_location: 'true'
login_username_placeholder: 'Interlochen ID # or barcode'
login_page_message: 'Please log in to access your library account'
