machine_readable: 'icamr.tadl.net'
public_catalog: 'https://myaccount.ica.tadl.net'
elastic_evergreen_url: 'https://ica.elastic.tadl.org/main/index.json?query='
elastic_locations: [['ICA-ACADEMIC', '102'],['ICA-MUSIC', '103']]
logo: 'ica-logo.jpg'
error_image: '1x1.png'
cover_path_med: 'https://ica.tadl.net/opac/extras/ac/jacket/medium/r/'
cover_path_lg: 'https://ica.tadl.net/opac/extras/ac/jacket/large/r/'
long_pickup_locations: [['Academic', '102'],['Music', '103']]
location_options: [['Academic', '102']]
location_name: 'Interlochen Center for the Arts Library'
has_payments: 'false'
has_registration: 'false'
has_eresources: 'false'
account_only: 'true'
one_location: 'true'
login_username_placeholder: 'Interlochen ID # or barcode'
login_page_message: 'Please log in to access your library account'
