location_name: 'Kalkaska County Library'
elastic_evergreen_url: 'https://elastic-evergreen-kcl.apps.tadl.org/main/index.json?query='
pickup_locations: [['Kalkaska', '44']]
location_options: [['Kalkaska', '44']]
long_pickup_locations: [['Kalkaska County Library', '44']]
elastic_locations: [['KCL', '44']]
all_locations_code: '44'
has_payments: 'false'
has_registration: 'false'
has_eresources: 'false'
opac_toggle: [{'name': 'Main', 'url': 'https://new-catalog.kalkaskalibrary.org/main/index'},{'name': 'Youth', 'url': 'https://youth-catalog.kalkaskalibrary.org/main/index'},{'name': 'Teen', 'url': 'https://teen-catalog.kalkaskalibrary.org/main/index'}]
system_lock:
  card_prefix_allow: '90247'
