system_name: 'KCL'
machine_readable: 'mr-v2a.catalog.tadl.org'
public_catalog: 'https:/catalog.kalkaskalibrary.org'
location_name: 'Kalkaska County Library'
elastic_evergreen_url: 'https://kcl-elastic.apps.tadl.org/main/index.json?query='
logo: 'kcl-logo.jpg'
error_image: 'kcl-logo.jpg'
pickup_locations: [['Kalkaska Main Branch', '44'],['Coldsprings', '56'],['Garfield Township', '57']]
location_options: [['All Locations', '43'],['Kalkaska Main Branch', '44'],['Coldsprings', '56'],['Garfield Township', '57']]
long_pickup_locations: [['Kalkaska County Library Main Branch', '44'],['Coldsprings Township Hall Branch Library', '56'],['Garfield Township Hall Branch Library', '57']]
elastic_locations: [['KCL', '44'],['KCL-COLD', '56'],['KCL-GARF', '57']]
all_locations_code: '43'
has_payments: 'false'
has_registration: 'true'
has_eresources: 'false'
register_form: '/register/new'
register_location: '44'
additional_nav_links:
  - name: 'Website'
    href: 'https://www.kalkaskalibrary.org/'
opac_toggle: [{'name': 'Main', 'url': 'https://catalog.kalkaskalibrary.org/main/index'},{'name': 'Youth', 'url': 'https://youth-catalog.kalkaskalibrary.org/main/index'},{'name': 'Teen', 'url': 'https://teen-catalog.kalkaskalibrary.org/main/index'}]
passreset_text: 'Forgot password?'
system_lock:
  card_prefix_allow: '90247'
show_ancestory: true
home_link_text: 'Home'
melcat_search: true
system_synonym: 'district'
show_consumerreports: true
