system_name: 'KPS'
machine_readable: 'mr-v2.catalog.tadl.org'
public_catalog: 'https://kps-catalog.kalkaskalibrary.org'
location_name: 'Kalkaska Public Schools'
elastic_evergreen_url: 'https://kps.elastic.tadl.org/main/index.json?query='
logo: 'kps-logo.jpg'
error_image: 'kps-logo.jpg'
pickup_locations: [['Birch Street Elementary', '48'], ['Cherry Street Intermediate', '49'], ['Rapid City Elementary', '50']]
location_options: [['All Locations', '47'], ['Birch Street Elementary', '48'], ['Cherry Street Intermediate', '49'], ['Rapid City Elementary', '50'], ['Kalkaska County Library', '44']]
long_pickup_locations: [['Birch Street Elementary', '48'], ['Cherry Street Intermediate', '49'], ['Rapid City Elementary', '50']]
elastic_locations: [['KCL', '44'], ['KPS', '47'], ['KPS-BSE', '48'], ['KPS-CSI', '49'], ['KPS-RCE', '50']]
all_locations_code: '47'
has_payments: 'false'
has_registration: 'false'
has_eresources: 'false'
register_form: '/register/new'
register_location: '47'
#opac_toggle: [{'name': 'Birch Street Elementary', 'url': 'https://kps-bse-light.opac.tadl.org/main/index'},{'name': 'Cherry Street Intermediate', 'url': 'https://kps-csi-light.opac.tadl.org/main/index'},{'name': 'Rapid City Elementary', 'url': 'https://kps-rce-light.opac.tadl.org/main/index'}]
passreset_text: ' '
show_ancestory: false
home_link_text: 'Home'
melcat_search: false
