system_name: 'TADL'
machine_readable: 'mr-v2.catalog.tadl.org'
public_catalog: 'https://catalog.tadl.org'
location_name: 'Traverse Area District Library'
elastic_evergreen_url: 'https://tadl.elastic.tadl.org/main/index.json?query='
logo: 'logo-clock-only.png'
error_image: 'logo-clock-only.png'
pickup_locations: [['Woodmere', '23'],['Interlochen', '24'],['Kingsley', '25'],['Peninsula', '26'],['Fife Lake', '27'],['East Bay', '28']]
location_options: [['Woodmere', '23'],['All Locations', '22'],['Interlochen', '24'],['Kingsley', '25'], ['Peninsula', '26'], ['East Bay', '28'], ['Fife Lake', '27']]
long_pickup_locations: [['Woodmere (Main) Branch', '23'],['Interlochen Public Library', '24'],['Kingsley Branch Library', '25'],['Peninsula Community Library', '26'],['Fife Lake Public Library', '27'],['East Bay Branch Library', '28']]
elastic_locations: [['TADL-WOOD', '23'],['TADL-IPL', '24'],['TADL-KBL', '25'], ['TADL-PCL', '26'], ['TADL-EBB', '28'], ['TADL-FLPL', '27']]
all_locations_code: '22'
has_registration: 'true'
register_newsletter: 'true'
register_form: '/register/new'
register_location: '23'
register_agreement_text: 'tadl'
register_button: 'true'
register_location_name: 'any Traverse Area District Library location'
register_listapi_url: 'https://www.tadl.org/listapi/tadl/'
has_payments: 'true'
payment_link: 'https://www.tadl.org/pay/pay.cgi'
has_eresources: 'true'
passreset_text: 'Forgot password?'
# system_lock:
#   card_prefix_prevent: '90247'
summer_reading: 'false'
summer_start_date: 3 June 2019
summer_report_date: 17 June 2019
sms_notify: true
